mode: debug                  # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: qiandaoqitong          # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数

        # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数

# 数据库配置
db:
  name: sgnInSys
  addr: 8.134.173.123:8001
  username: root
  password: 123456